spring:
  datasource:
    url: jdbc:postgresql://postgres-user:5432/users
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false