spring:
  datasource:
    url: jdbc:postgresql://users-db:5432/users_db
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false